version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ballistics
      - FLASK_ENV=production
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ballistics
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - "443:443"
    depends_on:
      - app
    networks:
      - appnet

volumes:
  postgres_data:

networks:
  appnet:
    driver: bridge